/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: eebba2c8750f8ca9b6d2b2ddc5b0d440)
interface __BaseEnv_Env {
	REPOSITORY: "kmshdev/foundation-models-utilities";
	LINEAR_PROJECT_NAME: "Engineering Workflow Automation";
	OWNER_TOKEN: string;
	RUNNER_SIGNING_KEY: string;
	GITHUB_TOKEN: string;
	LINEAR_TOKEN: string;
	COORDINATOR: DurableObjectNamespace<import("./src/index").EngineeringCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "EngineeringCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REPOSITORY" | "LINEAR_PROJECT_NAME" | "OWNER_TOKEN" | "RUNNER_SIGNING_KEY" | "GITHUB_TOKEN" | "LINEAR_TOKEN">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}